sudo: required

services:
- docker

language: scala

scala:
- 2.12.8

env:
  global:
  - DOCKER_REPO: wbaa/rokku-sts
  - secure: 4Lp+bz7To+oBWw7T/y9XRb46opqxp9NvtDcT0OYGvnkbuMhLLzL5E9P9VhM0PujjB12dmm2zLP8tB1rHVsn7g1LzSILjiES7q53C5bt9wcwF0e7T885+cas4cwgHz8IoLewgG0TOwnZIsyAAwgSQMWbqU3neF7MApdiSQNQ2BI/NW/UO51MJ9RP3Qld0HzbJEZA6x0r5YGQN4JPLcoz9SI9VWIAmMz2ciy4kRgVpOBnWkWPLyOLXcRdcMyfjHBm4iLi4yazigN/G7erU21NFPbHgxEZwj8c4MuSKWuwbmTFAEaT3LkGnstZ8sYdLgF/d3a0z8U7v7Ul955sVM4iJRciUKUJpFgqrMDET7zC7jGihJc2tL2qFQoHiKN9LFv88wRDyprxDK13A9BptdO9fr401qI/PngXJNNfgeo083yZE+zK91oqtLBK9AHboCiSKnl30qKWUOczlpeoUMl5eZyv4IV8xK7YG9KOGkx4kglh00VZ815p9GpubwZ2PhbUWX6zFs3qMjmUgwQnmtLoZTKqUxoyu+OemTJw24wYp58NU5tHM85kQS0SLwP1zUTa5GLm8rxdd7+iPHF2Jr2TDs2eS1C6JtQoTL/l80rI1Kfu8tlndGEZg0xh8BegaQ6gKIYGXcZb9y32yBDkH1snA+pmh/4QnaZogyyuhykx2adA=
  - secure: NfG4oBVLO+f8cUw9fLmIPDpK1Y1i9Y6iGAzE0Ug6YzCKw6WeVqrUrTYfDoXfRDIXoRSJ8tSufoLql1+qBix9LWRb41p+O1rb5v+IdBqZI6D3f0Y2r8uFjs0HvkVwDDTAiUNPueRPcdH8CK0xaTBTu0ITxB9PyaoPTAoL1RjxrN2DGg75jwFJ89ViuE8f5zPXvD7eoa2bmNMqhquDXv/QR56zdK+m3sKEV7SeIbeKIekiwP/bqcTZ/Jon/PxVntfET04nneaXLbMICoyszHRv2zxg2YEpf15OlT8b0JT/9Gs7xLD5gDJ+P2geuN5rJKiRgIl+yzeTL3SN0HT6kAO2JkqSjLjWLFeul33ax39nukv8+Hx+SLOh0qD0UTLWsM9EdyKQqi56MNzJPJt3PUElVeD1Bdl/26IpLO70btleyHBPXXjtxPQArYSmPwNy0uC+E7kqquKrnvVsQ+lAE9VgznEUHqj5mmUIl9XO2eHq2F5wls7ter9nagM0VyrDnQFmZBt6KO3BfnOCAnIm9wMIWy2kak+BIkJ6lJjL+PHraK0hIFGLGY+bx/OyRGQNHeRsAWjEV1QAjJ1lWmHjgumahK7d+D5LLcicUto36BQ6G8BH4ZgMODxhE0T8mB7nEMLDMkNJnsXIsbi1kiOaSXZVrdMn2Gs9iFU9dQFS2mdoyO0=

before_script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- echo "Starting dependent containers for testing"
- docker-compose up -d
- echo "Compile the project while containers are starting up"
- sbt ++$TRAVIS_SCALA_VERSION clean compile
- echo "Wait for containers to be up and running"
- bash waitForContainerSetup.sh

script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)
- export AIRLOCK_STS_VERSION="${TRAVIS_BRANCH/\//_}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [ "${TRAVIS_BRANCH}" != "master" ]; then
    echo "Build image for with name $DOCKER_REPO:$AIRLOCK_STS_VERSION";
    sbt clean docker:publish;
  fi
- if [ -n "$TRAVIS_TAG" ]; then
    docker tag $DOCKER_REPO:$AIRLOCK_STS_VERSION $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
  fi
