sudo: required

services:
- docker

language: scala

scala:
- 2.12.6

env:
  global:
  - DOCKER_REPO: nielsdenissen/airlock-sts
  - secure: nJFXIjug4URAlsKAinB4WTnxfL2kmSY+1LJ6A7lcUSCkm9O0segynBbyeAVurgV8b3pS5iG8ZRqbJk28xxK5Wo+PRH8L7ywpB2CT8Au+Rgv5T68yfWUyscB8/YasR1j6PfAFyqixzKSfqyI5JAPo0gvHjVklZsOHxQzLBnvDK+yluOiENJEixN3GaOjRCayIQzpJWse9MQqHdIhfEOGzyxLRhbfFn3pbP8UQMKX5kyWUN9IXAB5oz7b4a0F5pzC9VYrmLl1u6J3g7LtLBjEqDetlOJD5P/jtDbFxm4xXLV6TF5UyMnDX7fQjTDH2JPaAqy6GeBgXBYG4gL3k2XI36jbSgn1OMYXB78u/r1vulm+ybbQNVx1irbkSi4t1AYsCxOXBdtyipXXwHibXPUOFXMEoXuvXBeXnekAqrTAf3W0oeLtqZKesN3LX3GMGEvOg9tJ560w2vre+KwJdVRfSTwk3C0J6ymHsiE8v6I5aLHyEi+umWnyd+a8N7LToyBHF/LnHRq+dzwUDInGQBDdHJmUyyzhsv8mQXlF+suUJUfil4kAGYtnW4w2D1xDDKzdJUPJ/M3G30kVSZtVzhVTKR/um1bJY+kzclKw8W6jZUrF7BK7mbt9yNxWUcuinxnsbcNwEDpwiBh+UTEToEA1CTTHyFyfglZaHZg+DdNHvXz4=
  - secure: GQSRXKLKww2Pnh1FNnTLGEOGGe6GB2Pdbh5E+Tzbm5IFVhjfvDQ6YLbu87c5kYSbW5AV8serhhYKWFCJPQmbOpDIUN0J61XX77xKfgH6YvLIu4i3no9lSMMJnza5f0GGFx43t9BJLitUaAYVzIaVzFcqCUI2uXfLikfmYQ0xE+nqTuHnJ/hIq+kSi8BhoyFLMRhIEpqKvulVnQHCTHy7eEjcPBw0EVtSQJ4SCF2QBocNzKRz7Mmh1xk16f38noz8gtF8BaKoknFB0W0LUpAubvDrxh4wRDGUZzqNpH1G58N/csxUUzW11CVc9Xsvc5PLtcLLYR1vDiS9YgYImYaaY2hin3/yGqROIX90fwl71r0Bum9+P0ZXOXNZCWZYmzU2bHh4Kca4ka1V+n15Y8ZRtK5Y4x5GM3JP/Ird6UMjr+gYYjwEYTqMvxc6fzDkhRlfbKRWKAbLgB6LNKzozU1KKZxGbeERLDhrzgnHsdObC7PRAi5xAFRBKQeSyqHDxCBA0MWnZ/NpAKOYf+tu0Lx9iNDUuE1PGu6tjdSX0Gpch8bsQ2nkVmHRRVNHk9QV+ZYRYtJi/ZoQRlVrAmOX3BCrnO/0GTNt4sk6QrRxeEkYbw4Guqj3lNOG6nrXURybrUmy4Ul2zdWXURicxrmfIDx4fcx2/rJTz36NoyPmsV30w9Q=

before_script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- echo "Starting dependent containers for testing"
- docker-compose up -d
- echo "Compile the project while containers are starting up"
- sbt ++$TRAVIS_SCALA_VERSION clean compile
- echo "Wait for containers to be up and running"
- bash waitForContainerSetup.sh

script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)
- export DOCKER_TAG="${TRAVIS_BRANCH/\//_}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [ "${TRAVIS_BRANCH}" != "master" ]; then
    echo "Build image for with name $DOCKER_REPO:$DOCKER_TAG";
    sbt clean docker:publish;
  fi
- if [ -n "$TRAVIS_TAG" ]; then
    docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
  fi
