version: "2"
services:

  keycloak:
    image: wbaa/airlock-dev-keycloak:0.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080

  mariadb:
    image: wbaa/airlock-dev-mariadb:0.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3307:3306
