version: "2"
services:

  keycloak:
    image: kr7ysztof/keycloak-it:0.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080

  # TODO: use tagged image of mariadb from dockerhub
  mariadb:
    image: testmaria:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
